language: go

go:
- "1.13"

# $TRAVIS_GOARCH hack - see https://github.com/travis-ci/travis-ci/issues/6126

env:
  matrix:
    - TRAVIS_GOARCH=amd64
    - TRAVIS_GOARCH=386

before_install:
 - export GOARCH=$TRAVIS_GOARCH

install:
 - go get -u github.com/slayercat/gosnmp
 - go get github.com/stretchr/testify/assert
 - go get -u golang.org/x/tools/cmd/goimports

script:
 - go build .
 - go test -v .
